title: "Kira Wei's Data Science And Analytics Portfolio"
description: "Kira Wei: Data Scientist | Pricing Optimization Professional | Business Analyst | Travel Industry | Grocery Retail Industry"
show_downloads: false
theme: jekyll-theme-cayman